### PR TITLE
Use HTTPS where possible

### PR DESCRIPTION
**Pull request by mathiasbynens**
This avoids the mixed content warning on https://anvaka.github.io/npmrank/online/.

### CODE REVIEW

**Comment by anvaka** [comment]
Thank you!

**Comment by anvaka** [comment]
Looks like https://fb.me/react-with-addons-0.11.1.min.js gives 301 to http hosted library. I'm going to just include the library into repository.

**Comment by mathiasbynens** [comment]
Weird; it redirects to an HTTPS URL for me… But that might be because I’m using HTTPS Everywhere browser extension.

**Update:** confirmed.

**Comment by mathiasbynens** [comment]
Anyway, now that this is resolved, you may want to update the project’s URL to the HTTPS version, here:

**Comment by anvaka** [comment]
Good point. Done.

**Comment by mathiasbynens** [comment]
:+1: :rocket:

**Pull request merged**
